services:
  odoo-staging:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.staging
    image: odoo_multibikes:staging
    container_name: odoo-staging
    depends_on:
      db-staging:
        condition: service_healthy
    expose:
      - "8069"
      - "8072"
    networks:
      - odoo-network
      - npm-odoo
      - default
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - ./custom-addons:/mnt/extra-addons:cached
      - odoo-data-staging:/var/lib/odoo
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    env_file:
      - ./env/Staging.env
      - ./env/Database_staging.env
    restart: unless-stopped


  # Base de données principale pour staging
  db-staging:
    image: postgres:15
    env_file:
      - ./env/Database_staging.env
    networks:
      - odoo-network
    volumes:
      - postgres-data-staging:/var/lib/postgresql/data
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped


networks:
  default:
  odoo-network:
    driver: bridge
  npm-odoo:
    external: true

volumes:
  postgres-data-staging:
  odoo-data-staging: