services:
  odoo-dev:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.dev
    image: odoo_multibikes_dev:local
    container_name: odoo-dev
    depends_on:
      db-dev:
        condition: service_healthy
    expose:
      - "8069"
      - "8072"  # Port WebSocket
    networks:
      - odoo-network
      - npm-odoo
      - default
    volumes:
      - ./custom-addons:/mnt/extra-addons:delegated
      - odoo-data-dev:/var/lib/odoo
    env_file:
      - ./env/Dev.env
      - ./env/Database_dev.env
    restart: unless-stopped

  # Base de données principale pour dev
  db-dev:
    image: postgres:15
    env_file:
      - ./env/Database_dev.env
    networks:
      - odoo-network
    volumes:
      - postgres-data-dev:/var/lib/postgresql/data
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

networks:
  default:
  odoo-network:
    driver: bridge
  npm-odoo:
    external: true

volumes:
  postgres-data-dev:
  odoo-data-dev:
