FROM ghcr.io/maelcatteau/odoo-ee-base_2:18.0

# Installer pdfminer.six
USER root
RUN pip3 install pdfminer.six
# Copier le script en tant que root (avant USER odoo)
COPY scripts/entrypoint_staging.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh && chown odoo:odoo /entrypoint.sh

# Exposition des ports
EXPOSE 8069 8072

# Revenir à l'utilisateur odoo
USER odoo

# Point d'entrée
ENTRYPOINT ["/entrypoint.sh"]
