# ./dockerfiles/Dockerfile.app
FROM ghcr.io/maelcatteau/odoo-ee-base:18.0

# Temporairement root pour copier les scripts et changer les permissions
USER root 

# Copier les scripts nécessaires
COPY ./scripts/entrypoint_dev.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Créer et configurer le répertoire pour les rapports de test
RUN mkdir -p /test-reports && \
    chmod 777 /test-reports

# S'assurer que les répertoires pour les volumes existent et ont les bonnes permissions
RUN mkdir -p /mnt/extra-addons /etc/odoo /var/lib/odoo /var/log/odoo && \
    chown -R odoo:odoo /mnt/extra-addons /etc/odoo /var/lib/odoo /var/log/odoo

# Les volumes seront gérés par docker-compose
VOLUME ["/var/lib/odoo", "/mnt/extra-addons", "/etc/odoo", "/test-reports"]

EXPOSE 8069 8072

USER odoo

ENTRYPOINT ["/entrypoint.sh"]
# Important: nous spécifions simplement "odoo" comme commande de démarrage
CMD ["odoo"]
