from . import test_mb_renting_day_config
from . import test_mb_renting_period
from . import test_mb_renting_stock_period_config
from . import test_product_pricing
from . import test_product_template
from . import test_product_product
from . import test_res_company
from . import test_res_config_settings
from . import test_stock_warehouse
